@startuml
Title "ZArcgis类图"

namespace 工具类{
    class GisCalloutMgr
    class GeoCoordinateConvertUtil
    class WktConvertUtil
}

class GisMapView

namespace 图层管理类{
    GisAbstractGraphicsOverlay<|-- GisGraphicsLayer
    GisAbstractOperationalLayer<|-- GisFeatureLayer
    GisFeatureLayer<|-- GisGeoDatabaseLayer
    GisFeatureLayer<|-- GisShapeFileLayer
    GisAbstractOperationalLayer<|-- GisMapImageLayer
    GisGraphicsLayer.>GisGraphicsOverlayConfig
    
    
    abstract class GisAbstractGraphicsOverlay{
        + GisAbstractGraphicsOverlay(GisMapView mapView)
    }
    
    abstract class GisAbstractOperationalLayer{
        + GisAbstractOperationalLayer(GisMapView mapView)
    }
    
    class GisGraphicsOverlayConfig{
        + static GisGraphicsOverlayConfig instanceBuffer()
        + static GisGraphicsOverlayConfig instanceHighlight()
        + static GisGraphicsOverlayConfig instanceDraw()
    }
}

图层管理类-->GisMapView
RelativeLayout<|--GisMapOperateView
FrameLayout<|--GisMapView
GisMapOperateView-->GisMapView
GisMapOperateView<->GisMenuBar
GisMenuBar-->GisMapTypeDialog
GisMapOperateView-->GisMapConfig
GisMapView-->GisMapConfig


class GisMapOperateView{
    - GisGraphicsLayer gisGraphicsLayer
}

class GisMapView{
    + void init(GisMapConfig gisMapConfig)
    + void zoomToCenterScale()
    + void zoomToPoint(Point point)
    + void zoomToPoint(double x, double y, double scale)
    + void zoomToGeometry(Geometry geometry)
    + void setCenterPoint(double[] centerPoint)
}

abstract class BaseTiledParam
BaseTiledParam<|--BaiduTiledParam
BaseTiledParam<|--GaodeAndGoogleTiledParam
BaseTiledParam<|--GaodeTiledParam
BaseTiledParam<|--GoogleTiledParam
BaseTiledParam<|--TiandituTiledParam
BaseTiledParam-->GisMapConfig
BaseTiledLayer-->BaseTiledParam
GisMapView..>BaseTiledLayer

MeasureDraw<|--GisMeasureDraw
MeasureDraw..>MeasureDrawEntity
GisMeasureDraw..>MeasureUtil
GisMenuBar-->GisMeasureDraw
@enduml